const logoUrl = new URL('../assets/logo.svg', import.meta.url).href;
import { escapeHtml } from './ui.js';

/** @param {import('../core/types.js').Sequence[]} sequences */
export function workspaceMarkup(sequences) {
    return `<section class="workspace-home">
      <div class="workspace-heading"><div><span class="eyebrow" data-en="YOUR LAB, IN THE BROWSER" data-vi="PHÒNG THỰC HÀNH TRONG TRÌNH DUYỆT">YOUR LAB, IN THE BROWSER</span>
        <h1><span data-i18n="Your sequence workspace">Your sequence workspace</span></h1><p><span data-i18n="Explore DNA, RNA and proteins — start with a sequence.">Khám phá DNA, RNA và protein — bắt đầu từ một trình tự.</span></p></div>
        <button class="ws-primary" data-workspace-action="import"><span data-i18n="↑ Import sequences">↑ Import sequences</span></button></div>
      <div class="learning-banner"><div><span class="eyebrow"><span data-i18n="FIRST STEPS">BẮT ĐẦU TẠI ĐÂY · FIRST STEPS</span></span>
        <h2><span data-i18n="From DNA to protein">Từ DNA đến protein</span></h2><p><span data-en="New to bioinformatics? Follow 3 short steps. We prepare the sample and explain each result." data-vi="Mới học tin sinh học? Làm theo 3 bước ngắn. Ứng dụng chọn sẵn mẫu và giải thích từng kết quả.">Mới học tin sinh học? Làm theo 3 bước ngắn.</span></p>
        <button class="ws-primary" data-workspace-action="learn"><span data-en="Start my first lesson →" data-vi="Bắt đầu bài học đầu tiên →">Bắt đầu bài học đầu tiên →</span></button></div>
        <div class="learning-sequence" aria-hidden="true"><img class="learning-brand" src="${logoUrl}" alt="" width="48" height="48"><span>DNA</span><b>ATG <em>GTG</em> AGC</b><i><span data-i18n="↓ Translation">↓ Translation</span></i><b>M <em>V</em> S</b><span>PROTEIN</span></div></div>
      <div class="workspace-shortcuts">
        <button data-workspace-action="library"><span class="shortcut-number">01</span><span><strong data-en="Learn with examples" data-vi="Học qua ví dụ">Learn with examples</strong><small data-en="Sample sequences · guided practice" data-vi="Mẫu có sẵn · thực hành từng bước">Sample sequences · guided practice</small></span><span aria-hidden="true">↗</span></button>
        <button data-workspace-action="database"><span class="shortcut-number">02</span><span><strong data-en="Explore databases" data-vi="Khám phá dữ liệu">Explore databases</strong><small data-en="NCBI & UniProt · search and import" data-vi="NCBI & UniProt · tìm và nhập">NCBI & UniProt · search and import</small></span><span aria-hidden="true">↗</span></button>
      </div>
      <div class="workspace-heading compact"><div><h2><span data-i18n="Documents">Documents</span> <span class="ws-count">${sequences.length}</span></h2><p><span data-i18n="Select a name to open. bp: nucleotide · aa: amino acid.">Chọn tên để mở. bp: nucleotide · aa: amino acid.</span></p></div>
        <button class="ws-secondary" data-workspace-action="new"><span data-i18n="+ New sequence">+ New sequence</span></button></div>
      <div class="document-filters"><input id="workspace-search" type="search" placeholder="Filter by name…" data-i18n-placeholder="Filter by name…" aria-label="Filter workspace documents" data-i18n-aria-label="Filter workspace documents">
        <div class="document-type-filters" role="group" aria-label="Sequence type" data-i18n-aria-label="Sequence type">${['all', 'dna', 'rna', 'protein'].map(type => `<button type="button" data-workspace-type="${type}" aria-pressed="${type === 'all'}"><span ${type === 'all' ? 'data-vi="Tất cả" data-en="All"' : ''}>${type === 'all' ? 'Tất cả' : type.toUpperCase()}</span><span class="filter-count">${type === 'all' ? sequences.length : sequences.filter(s => s.type === type).length}</span></button>`).join('')}</div></div>
      <p class="document-result-count" id="workspace-result-count" role="status" aria-live="polite"></p>
      <div class="document-table-wrap"><table class="document-table"><thead><tr><th><span data-i18n="Name">Name</span></th><th><span data-i18n="Type">Type</span></th><th><span data-i18n="Length">Length</span></th><th><span data-i18n="Topology">Topology</span></th><th class="document-detail"><span data-i18n="Features">Features</span></th><th><span data-vi="Mở nhanh" data-en="Quick access">Mở nhanh</span></th></tr></thead><tbody>
        ${sequences.map((s, i) => `<tr data-document-row data-name="${escapeHtml(s.name.toLowerCase())}" data-type="${s.type}"><td><button data-open-document="${i}">${escapeHtml(s.name)} <span>↗</span></button></td><td><span class="type-pill">${s.type.toUpperCase()}</span></td><td class="mono">${s.sequence.length.toLocaleString()} ${s.type === 'protein' ? 'aa' : 'bp'}</td><td class="document-topology"><span data-i18n="${s.topology === 'circular' ? 'Circular' : 'Linear'}">${s.topology === 'circular' ? 'Circular' : 'Linear'}</span></td><td class="document-detail">${s.features?.length || 0}</td><td class="document-quick-actions"><button data-open-document="${i}" data-document-tool="${s.type === 'protein' ? 'protein3d' : 'linearmap'}"><span data-vi="${s.type === 'protein' ? 'Xem 3D' : 'Bản đồ'}" data-en="${s.type === 'protein' ? 'View 3D' : 'Map'}">${s.type === 'protein' ? 'Xem 3D' : 'Bản đồ'}</span></button><button data-open-document="${i}" data-document-tool="stats"><span data-vi="Thống kê" data-en="Statistics">Thống kê</span></button></td></tr>`).join('')}
      </tbody></table><p id="workspace-no-results" hidden><span data-i18n="No matching sequences. Try another name or type.">No matching sequences. Try another name or type.</span></p></div>
      <p class="workspace-footnote"><span data-i18n="Local workspace · Data is saved in this browser. Export to keep a copy.">Local workspace · Dữ liệu được lưu trong trình duyệt này. Export để giữ bản sao của bạn.</span></p>
    </section>`;
}
